# Site settings
title: Your Site Title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. This will appear in search results.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol, e.g. http://example.com
twitter_username: username
github_username: username

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Navigation
header_pages:
  - about.md
  - blog.md
  - contact.md

# Custom settings
author: Your Name
logo: /assets/images/logo.png
hero_image: /assets/images/hero.jpg
hero_text: Your Engaging Headline Here
hero_subtext: A brief description that captures visitor attention

# Collections
collections:
  featured:
    output: true
    permalink: /:collection/:name/

# Default front matter settings
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Your Name"
      image: "/assets/images/default-post.jpg"
  - scope:
      path: ""
      type: "featured"
    values:
      layout: "feature"
  - scope:
      path: ""
    values:
      layout: "default"
